import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header style={{ background: "#000", padding: "1rem" }}>
          <h2 style={{ color: "#fff " }}>Header</h2>
        </header>
        {children}
        <footer style={{ background: "#000", padding: "1rem" }}>
          <h2 style={{ color: "#fff" }}>Header</h2>
        </footer>
      </body>
    </html>
  );
}
